info:
  name: Create Task - Título muy corto
  type: http
  seq: 6

http:
  method: POST
  url: "{{baseUrl}}/api/tasks"
  body:
    type: json
    data: |-
      {
        "title": "ab"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
