info:
  name: Create Task - Fecha en formato incorrecto
  type: http
  seq: 8

http:
  method: POST
  url: "{{baseUrl}}/api/tasks"
  body:
    type: json
    data: |-
      {
        "title": "Tarea válida",
        "due_date": "01/05/2026"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
