info:
  name: Create Task
  type: http
  seq: 4

http:
  method: POST
  url: "{{baseUrl}}/api/tasks"
  body:
    type: json
    data: |-
      {
        "title": "Mi primer tarea",
        "description": "Descripción de prueba",
        "priority": "high",
        "due_date": "2026-05-01"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
