info:
  name: Create Task - Sin título
  type: http
  seq: 5

http:
  method: POST
  url: "{{baseUrl}}/api/tasks"
  body:
    type: json
    data: |-
      {
        "description": "Sin título"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
