info:
  name: Get Task - Acceso a tarea de otro usuario
  type: http
  seq: 10

http:
  method: GET
  url: "{{baseUrl}}/api/tasks/1"
  auth:
    type: bearer
    token: "{{tokenUser}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
