info:
  name: Update Task
  type: http
  seq: 12

http:
  method: PUT
  url: "{{baseUrl}}/api/tasks/1"
  body:
    type: json
    data: |-
      {
        "status": "in_progress",
        "priority": "critical"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
